import React, {Component} from 'react';

var filter_Response_By_Seq = []
var new_Array_Push_Data = [];

 class Images_api extends Component {

  constructor(props) {
    super(props)
    this.state = {
    selectedCustomer: 1,
    catergoires: {  
         "items": [
        {
            "Id": 300000385874751,
            "RecordName": "PORTAL-0000001",
            "CreatedBy": "kjell.nygaard",
            "CreationDate": "2021-02-19T00:59:42+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:38:12+00:00",
            "RecordNumber": "FSN4637018",
            "LastUpdateLogin": null,
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000382626885,
            "OraZcxOwner_c": "Kjell Nygaard",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/etc/dam/viewers/s7viewers/html5/BasicZoomViewer.html?asset=/content/dam/public-videos/support/SupremeDescaleThumbnail.jpg&config=/etc/dam/presets/viewer/Zoom_light&serverUrl=https://keurig-h.assetsadobe.com/is/image/&contenturl=/",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "1_EXT_COLD_HOMEPAGE_NUTRITION_FACTS",
            "PageSection_c": "LINKS",
            "SubType_c": "HYPERLINK",
            "SearchTerm_c": null,
            "HyperLinkURL_c": "https://www.keurig.com/",
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_300000386144691",
            "ContentType_c": null,
            "ParentCategory_c": null,
            "FAQs_c": null,
            "English_c": null,
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": null,
            "Sequence_c": null
        },
        {
            "Id": 300000385874752,
            "RecordName": "PORTAL-0000002",
            "CreatedBy": "kjell.nygaard",
            "CreationDate": "2021-02-19T01:07:02.660+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:38:24.375+00:00",
            "RecordNumber": "FSN4637019",
            "LastUpdateLogin": null,
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000382626885,
            "OraZcxOwner_c": "Kjell Nygaard",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/content/dam/public-videos/support/Cleaning_Brewer.jpg",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "RECYLABILITY",
            "PageSection_c": "LINKS",
            "SubType_c": "HYPERLINK",
            "SearchTerm_c": "Category='RECYLABILITY'",
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": null,
            "FAQs_c": null,
            "English_c": null,
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": null,
            "Sequence_c": null
        },
        {
            "Id": 100000664777902,
            "RecordName": "PORTAL-0000004",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662210",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_HEADER",
            "PageSection_c": "HEADER",
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD",
            "FAQs_c": null,
            "English_c": "LEARN MORE ABOUT YOUR FAVORITE BEVERAGES",
            "Spanish_c": "MÁS INFORMACIÓN SOBRE TUS BEBIDAS FAVORITAS",
            "French_c": "EN SAVOIR PLUS SUR VOS BOISSONS PRÉFÉRÉES",
            "Notes_c": "Top Level Category",
            "Sequence_c": 1
        },
        {
            "Id": 100000664777903,
            "RecordName": "PORTAL-0000005",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662211",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_FAQS",
            "PageSection_c": "FAQS",
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD",
            "FAQs_c": null,
            "English_c": "For FAQs and articles, select a brand below…",
            "Spanish_c": "Para preguntas frecuentes y artículos, seleccione una marca a continuación …",
            "French_c": "Pour les FAQ et les articles, sélectionnez une marque ci-dessous…",
            "Notes_c": "Top Level Category",
            "Sequence_c": 2
        },
        {
            "Id": 100000664777904,
            "RecordName": "PORTAL-0000006",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662212",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/etc/dam/viewers/s7viewers/html5/BasicZoomViewer.html?asset=/content/dam/public-videos/support/SupremeDescaleThumbnail.jpg&config=/etc/dam/presets/viewer/Zoom_light&serverUrl=https://keurig-h.assetsadobe.com/is/image/&contenturl=/",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_FAQS_DR_PEPPER",
            "PageSection_c": "FAQS",
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_FAQS",
            "FAQs_c": null,
            "English_c": "N/A",
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Logo for Top 6 Brand",
            "Sequence_c": 1
        },
        {
            "Id": 100000664777905,
            "RecordName": "PORTAL-0000007",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662213",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/etc/dam/viewers/s7viewers/html5/BasicZoomViewer.html?asset=/content/dam/public-videos/support/SupremeDescaleThumbnail.jpg&config=/etc/dam/presets/viewer/Zoom_light&serverUrl=https://keurig-h.assetsadobe.com/is/image/&contenturl=/",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_FAQS_7UP",
            "PageSection_c": "FAQS",
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_FAQS",
            "FAQs_c": null,
            "English_c": "N/A",
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Logo for Top 6 Brand",
            "Sequence_c": 2
        },
        {
            "Id": 100000664777906,
            "RecordName": "PORTAL-0000008",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662214",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/etc/dam/viewers/s7viewers/html5/BasicZoomViewer.html?asset=/content/dam/public-videos/support/SupremeDescaleThumbnail.jpg&config=/etc/dam/presets/viewer/Zoom_light&serverUrl=https://keurig-h.assetsadobe.com/is/image/&contenturl=/",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_FAQS_AW",
            "PageSection_c": "FAQS",
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_FAQS",
            "FAQs_c": null,
            "English_c": "N/A",
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Logo for Top 6 Brand",
            "Sequence_c": 3
        },
        {
            "Id": 100000664777907,
            "RecordName": "PORTAL-0000009",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662215",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/etc/dam/viewers/s7viewers/html5/BasicZoomViewer.html?asset=/content/dam/public-videos/support/SupremeDescaleThumbnail.jpg&config=/etc/dam/presets/viewer/Zoom_light&serverUrl=https://keurig-h.assetsadobe.com/is/image/&contenturl=/",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_FAQS_CANADADRY",
            "PageSection_c": "FAQS",
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_FAQS",
            "FAQs_c": null,
            "English_c": "N/A",
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Logo for Top 6 Brand",
            "Sequence_c": 4
        },
        {
            "Id": 100000664777908,
            "RecordName": "PORTAL-0000010",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662216",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/etc/dam/viewers/s7viewers/html5/BasicZoomViewer.html?asset=/content/dam/public-videos/support/SupremeDescaleThumbnail.jpg&config=/etc/dam/presets/viewer/Zoom_light&serverUrl=https://keurig-h.assetsadobe.com/is/image/&contenturl=/",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_FAQS_SCHWEPPES",
            "PageSection_c": "FAQS",
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_FAQS",
            "FAQs_c": null,
            "English_c": "N/A",
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Logo for Top 6 Brand",
            "Sequence_c": 5
        },
        {
            "Id": 100000664777909,
            "RecordName": "PORTAL-0000011",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662217",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/etc/dam/viewers/s7viewers/html5/BasicZoomViewer.html?asset=/content/dam/public-videos/support/SupremeDescaleThumbnail.jpg&config=/etc/dam/presets/viewer/Zoom_light&serverUrl=https://keurig-h.assetsadobe.com/is/image/&contenturl=/",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_FAQS_SUNKIST",
            "PageSection_c": "FAQS",
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_FAQS",
            "FAQs_c": null,
            "English_c": "N/A",
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Logo for Brand",
            "Sequence_c": 6
        },
        {
            "Id": 100000664777910,
            "RecordName": "PORTAL-0000012",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662218",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_BRANDS",
            "PageSection_c": null,
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD",
            "FAQs_c": null,
            "English_c": "View All Brands",
            "Spanish_c": "Ver todas las marcas",
            "French_c": "Voir toutes les marques",
            "Notes_c": "Top Level Category",
            "Sequence_c": 3
        },
        {
            "Id": 100000664777911,
            "RecordName": "PORTAL-0000013",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662219",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_PST",
            "PageSection_c": null,
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD",
            "FAQs_c": null,
            "English_c": "Popular Search Topics",
            "Spanish_c": "Temas de búsqueda populares",
            "French_c": "Sujets de recherche populaires",
            "Notes_c": "Top Level Category",
            "Sequence_c": 4
        },
        {
            "Id": 100000664777912,
            "RecordName": "PORTAL-0000014",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662220",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_PST_NEW_PRODUCTS",
            "PageSection_c": null,
            "SubType_c": "KM_SEARCH",
            "SearchTerm_c": "EXT_COLD_PST_NEW_PRODUCTS",
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_PST",
            "FAQs_c": null,
            "English_c": null,
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Should trigger a blank KM search on the category listed",
            "Sequence_c": 1
        },
        {
            "Id": 100000664777913,
            "RecordName": "PORTAL-0000015",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662221",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_PST_PRODUCT_AVAILABILITY",
            "PageSection_c": null,
            "SubType_c": "KM_SEARCH",
            "SearchTerm_c": "EXT_COLD_PST_PRODUCT_AVAILABILITY",
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_PST",
            "FAQs_c": null,
            "English_c": null,
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Should trigger a blank KM search on the category listed",
            "Sequence_c": 2
        },
        {
            "Id": 100000664777914,
            "RecordName": "PORTAL-0000016",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662222",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_PST_PROMOTIONS",
            "PageSection_c": null,
            "SubType_c": "KM_SEARCH",
            "SearchTerm_c": "EXT_COLD_PST_PROMOTIONS",
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_PST",
            "FAQs_c": null,
            "English_c": null,
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Should trigger a blank KM search on the category listed",
            "Sequence_c": 3
        },
        {
            "Id": 100000664777915,
            "RecordName": "PORTAL-0000017",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662223",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_PST_ENVIRONMENTAL_SUSTAINABILITY",
            "PageSection_c": null,
            "SubType_c": "KM_SEARCH",
            "SearchTerm_c": "EXT_COLD_PST_ENVIRONMENTAL_SUSTAINABILITY",
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_PST",
            "FAQs_c": null,
            "English_c": null,
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Should trigger a blank KM search on the category listed",
            "Sequence_c": 4
        },
        {
            "Id": 100000664777916,
            "RecordName": "PORTAL-0000018",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662224",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_PST_SAFETY_QUALITY",
            "PageSection_c": null,
            "SubType_c": "KM_SEARCH",
            "SearchTerm_c": "EXT_COLD_PST_SAFETY_QUALITY",
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_PST",
            "FAQs_c": null,
            "English_c": null,
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Should trigger a blank KM search on the category listed",
            "Sequence_c": 5
        },
        {
            "Id": 100000664777917,
            "RecordName": "PORTAL-0000019",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662225",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_PST_COUPONS_PREMIUMPREQUESTS",
            "PageSection_c": null,
            "SubType_c": "KM_SEARCH",
            "SearchTerm_c": "EXT_COLD_PST_COUPONS_PREMIUMPREQUESTS",
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_PST",
            "FAQs_c": null,
            "English_c": null,
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Should trigger a blank KM search on the category listed",
            "Sequence_c": 6
        },
        {
            "Id": 100000664777918,
            "RecordName": "PORTAL-0000020",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662226",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": null,
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_LINKS",
            "PageSection_c": "LINKS",
            "SubType_c": null,
            "SearchTerm_c": null,
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD",
            "FAQs_c": null,
            "English_c": null,
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Dr Pepper Brand Detail Page Nutrition Fact Icon/Hyperlink. Should navigate the user to the Nutrition Fact URL in current browser tab",
            "Sequence_c": 5
        },
        {
            "Id": 100000664777919,
            "RecordName": "PORTAL-0000021",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662227",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/etc/dam/viewers/s7viewers/html5/BasicZoomViewer.html?asset=/content/dam/public-videos/support/SupremeDescaleThumbnail.jpg&config=/etc/dam/presets/viewer/Zoom_light&serverUrl=https://keurig-h.assetsadobe.com/is/image/&contenturl=/",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_LINKS_NUTRITION_FACTS",
            "PageSection_c": "LINKS",
            "SubType_c": "HYPERLINK",
            "SearchTerm_c": null,
            "HyperLinkURL_c": "https://www.keurig.com/",
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_LINKS",
            "FAQs_c": null,
            "English_c": "Nutrition Facts",
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Nutrition Fact Icon/Hyperlink. Should navigate the user to the Nutrition Fact URL in current browser tab",
            "Sequence_c": 1
        },
        {
            "Id": 100000664777920,
            "RecordName": "PORTAL-0000022",
            "CreatedBy": "APEXIT_CCTADMIN3",
            "CreationDate": "2021-02-27T09:39:11+00:00",
            "LastUpdatedBy": "APEXIT_CCTADMIN3",
            "LastUpdateDate": "2021-02-27T09:39:11+00:00",
            "RecordNumber": "FSN4662228",
            "LastUpdateLogin": "BC49358AE1052836E053A687550ACD6A",
            "ConflictId": 0,
            "UserLastUpdateDate": null,
            "CurrencyCode": "USD",
            "CurcyConvRateType": "Corporate",
            "CorpCurrencyCode": "USD",
            "OraZcxOwner_Id_c": 300000377520029,
            "OraZcxOwner_c": "CCTADMIN3 APEXIT",
            "Site_c": "COLD",
            "PageType_c": "HOMEPAGE",
            "VideoURL_c": null,
            "ImageURL_c": "https://dam.keurig.com/etc/dam/viewers/s7viewers/html5/BasicZoomViewer.html?asset=/content/dam/public-videos/support/SupremeDescaleThumbnail.jpg&config=/etc/dam/presets/viewer/Zoom_light&serverUrl=https://keurig-h.assetsadobe.com/is/image/&contenturl=/",
            "Product_Id_c": null,
            "Product_c": null,
            "Category_c": "EXT_COLD_LINKS_RECYCLABILITY",
            "PageSection_c": "LINKS",
            "SubType_c": "KM_SEARCH",
            "SearchTerm_c": "EXT_COLD_LINKS_RECYCLABILITY",
            "HyperLinkURL_c": null,
            "ActiveFlag_c": true,
            "SelectedRow": null,
            "CategoryId_c": "FUSION_CATEGORY_null",
            "ContentType_c": null,
            "ParentCategory_c": "EXT_COLD_LINKS",
            "FAQs_c": null,
            "English_c": "Recyclability",
            "Spanish_c": null,
            "French_c": null,
            "Notes_c": "Nutrition Fact Icon/Hyperlink. Should trigger a blank KM search on the category listed",
            "Sequence_c": 2
        }
    ],
   
},
    Category_Filter_Data:{},
    final_page_Load_Data : []
}
  }
  componentDidMount()
  {
   this.onPage_Load_Category_Filter()
  }

  onPage_Load_Category_Filter = function () {
    var i,j,k;
    for (i = 0; i <  this.state.catergoires.items.length; i++) {
        if(this.state.catergoires.items[i].ParentCategory_c === "EXT_COLD")
        {
          filter_Response_By_Seq.push(this.state.catergoires.items[i]);
        }
    }
   this.sortPageItems(filter_Response_By_Seq);
   new_Array_Push_Data = filter_Response_By_Seq;
   for (k = 0; k <  filter_Response_By_Seq.length; k++) {
    new_Array_Push_Data[k].children  = []
    for (j = 0; j <  this.state.catergoires.items.length; j++) {
        if(filter_Response_By_Seq[k].Category_c === this.state.catergoires.items[j].ParentCategory_c)
        {
          new_Array_Push_Data[k].children.push(this.state.catergoires.items[j]);
        }
   }
}
console.log("=====new_Array_Push_Data========",new_Array_Push_Data);
    this.setState({
        final_page_Load_Data:new_Array_Push_Data
   })
return new_Array_Push_Data;
 };

   sortPageItems = function (filter_Response_By_Seq) {
    filter_Response_By_Seq.sort(function(a, b) {
      return parseFloat(a.Sequence_c) - parseFloat(b.Sequence_c);
    });
  };


  render() {
    return (
    <div className="addmargin">
      Images Combine _NEW API
      <div>
      <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">First</th>
      <th scope="col">Last</th>
      <th scope="col">Handle</th>
    </tr>
  </thead>
  <tbody>
  
    {this.state.final_page_Load_Data.length >0 && this.state.final_page_Load_Data.map((data,key) =>
            <tr>
                <th scope="row">{data.Id}</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
                </tr>
            )}
            
  </tbody>
</table>
      
      </div>
     </div>
     )
  }

}
export default Images_api;